### ISSUE TITLE
MultiComboBox filter event exception

### ISSUE THREAD

**Issue by sunyoran** [vaadin-component-factory/multi-combo-box-flow#17]
A base usage of MultiComboBox as below:

![image](https://user-images.githubusercontent.com/46042932/111968362-06963680-8b34-11eb-9a8a-1c9b03188232.png)

Step 1. I filter an accurately item 'A01' as below:

![image](https://user-images.githubusercontent.com/46042932/111968408-11e96200-8b34-11eb-9d0c-a7c3b34d0dff.png)

Step 2. and then, click the popup option item as below:

![image](https://user-images.githubusercontent.com/46042932/111968451-1f065100-8b34-11eb-9d6a-4b189aa08b21.png)

Step 3. click mouse anywhere out of MultiComboBox, the strange behavior happened, MultiComboBox will clear.

**Comment by TatuLund** [comment]
Could you you attach code example that reproduces the problem. Preferably it should be an isolated view that can be easily copied to an existing project.

**Comment by jcgueriaud1** [comment]
Hi, I think this issue is for another component: https://vaadin.com/directory/component/multiselect-combo-box
Since the look in the screenshot looks very different than this component:
https://incubator.app.fi/multi-combo-box-flow-demo/in-memory

If it's the case you can open a ticket here: https://github.com/gatanaso/multiselect-combo-box-flow/issues
